### ISSUE TITLE
polyaxon command throws ImportError

### ISSUE THREAD

**Issue by eublefar** [polyaxon/polyaxon-cli#19]
Hi

After updating polyaxon-cli to 0.4.2 (from 0.4.1) it throws Import error.
```$ polyaxon 
Traceback (most recent call last):
  File "/home/mykyta/.local/bin/polyaxon", line 7, in <module>
    from polyaxon_cli.main import cli
  File "/home/mykyta/.local/lib/python3.6/site-packages/polyaxon_cli/main.py", line 9, in <module>
    from polyaxon_cli.cli.check import check
  File "/home/mykyta/.local/lib/python3.6/site-packages/polyaxon_cli/cli/check.py", line 14, in <module>
    from polyaxon_cli.schemas.polyaxonfile import PolyaxonFile
  File "/home/mykyta/.local/lib/python3.6/site-packages/polyaxon_cli/schemas/polyaxonfile.py", line 4, in <module>
    from polyaxon_schemas.polyaxonfile import PolyaxonFile  # noqa
ImportError: cannot import name 'PolyaxonFile'
```
I use Ubuntu 18.04 and Python 3.6.7.

**Comment by mouradmourafiq** [comment]
Someone else had similar issue when upgrading, not sure why pip has an strage behaviour sometime, I would suggest to make sure that your polyaxon requirements look similar to:

`pip freeze | grep polyaxon` :

```
polyaxon-cli==0.4.2
polyaxon-client==0.4.2
polyaxon-deploy==0.4.2
polyaxon-schemas==0.4.2
```

**Comment by eublefar** [comment]
Thanks, @mouradmourafiq.
I had all the packages you've mentioned on 0.4.2, but it seems pip keeps part of the older packages after the update, so I had to go over each package and uninstall it multiple times. 
Reinstalled clean version of cli works.
